### ISSUE TITLE
sendButton

### ISSUE THREAD

**Issue by Inginn** [Tenzer/alga#35]
is there a way to sendButton like in LGWebOSRemote
I like controlling my Plex from the keyboard.

**Comment by Tenzer** [comment]
It is not something I have implemented yet, as I've wanted to make sure the commands available in `alga` are the most useful ones, and they are named in a way that makes them intuitive to use. 

I had an idea, that if/when time would come to implement the functionality to send button presses, I would want it to be done in a more interactive UI, instead of having to send individual button presses as separate commands. A bit like a TUI version of the mobile app LG makes that also can work as a remote. 

Part of this, is because to send those button presses you first need to set up one WebSocket connection to the TV (like for all other commands) which you use to send a command that gives you back the address for a different WebSocket connection, where you can then connect and send the button presses. 

There's no obvious way to persist the connections across different invocations of `alga`, which means the connections have to be re-established for every button press. If there instead was a TUI interface which allowed you to send multiple button presses quickly after each other, the connections can be reused, making for much lower latency and a better experience in the end.

That said, it might be the `alga adhoc` command can be extended to support sending button presses, it could possibly be a good first step.

**Comment by Inginn** [comment]
I would think about allowing users to run the button commands, becaus I bind all my remote buttons with tiling window mangers so there is a usecase for not using a tui but individual commands. I allso bind everything like my tv rooms light to keyboard shortcuts so I only need my keyboard when watching tv.

examples from my hyperland.config using the broken LGWebOSRemote 
bind = $mainMod_ALT, RIGHT, execr, /opt/lgtv-venv/bin/lgtv --name TV --ssl sendButton right

this is usaly not used a lot at a time, just navigate plex/other tv app and selecting media, that way I dont need to pick up the remote.

**Comment by Tenzer** [comment]
I have implemented a new `alga remote send` command now which can be used for sending button presses. It has been released in version 1.2.0. Please give it a go!
